
#Author Farez
#Farez
#Bosen
import colorama
import time
from colorama import Fore, Back, Style
time.sleep(0.5)
print(Fore.RED + 'some red text')
print("part 1: hello")
time.sleep(5)
print("part 2: hello haha")
time.sleep(2.3)
name = str(input("input your name:"))
time.sleep(1.5)
print("hello",name)
time.sleep(2.5)
print("random password")
time.sleep(2.5)


import random
import string

# get random string of letters and digits
source = string.ascii_letters + string.digits
result_str = ''.join((random.choice(source) for i in range(8)))
print("passwordnya adalah",result_str)
time.sleep(2.5)

print("account hacking")
time.sleep(2.5)
print("  ~~~~~~~~~~~~~~~~~~~akun hacking~~~~~~~~~~~~~~~~~~~~~    ")

if input('TYPE "start" untuk memulai hack akun .\n> ') == 'start': 
 import time
time.sleep(3)
print("memulai menyambung ke tools ")
time.sleep(2)
print("PROCESS STARTED! ")
print(".     ")
time.sleep(1)
akun = input("akun name ? ->")
time.sleep(2.7)
print("memulai cek akun bernama",akun)
time.sleep(1)
haha = input("ingin mencek password akun?")
print("memulai")
time.sleep(2)
print("password ditemukan")
time.sleep(2.5)
print("tes all pasword")
time.sleep(1)
print("password Akhgajelas gagal")
time.sleep(0.5)
print("password 2999 gagal")
time.sleep(0.5)
print("password jujuun gagal")
time.sleep(0.5)
print("password Yeerkha234 gagal")
time.sleep(0.5)
print("password Yurtta2330 gagal")
time.sleep(0.5)
print("password yeera gagal")
time.sleep(0.5)
print("password geera gagal")
time.sleep(0.5)
print("password Hasuuu gagal")
time.sleep(0.5)
print("password kontolodon gagal")
time.sleep(2.5)
print("password asli ditemukan")
time.sleep(2.5)
print("                        ")
print("memulai mencari password")
time.sleep(2.5)
print("1%")
time.sleep(2.5)
print("10%")
time.sleep(2.5)
print("15%")
time.sleep(2.5)
print("20%")
time.sleep(2.5)
print("25%")
time.sleep(2.5)
print("30%")
time.sleep(2.5)
print("60%")
time.sleep(2.5)
print("75%")
time.sleep(2.5)
print("98%")
time.sleep(2.5)
print("100%")

print("password ditemukan")
time.sleep(2.5)
source = string.ascii_letters + string.digits
result_str = ''.join((random.choice(source) for i in range(8)))
print("passwordnya adalah",result_str)
print("saya stress")
print("saya stress")
print("saya stress")
print("saya stress")
halo = input("ingin dengar cerita hidup saya?")
time.sleep(1.5)
cerita = input("part 1: gw pernah suka ama orang namanya maisha ya itu dulu")
part = input("part 2: dan sekarang gw suka ama bianca and si bianca ternyata suka ama w juga haha")
time.sleep(1.7)
print("dah itu doang")
 

# Program to generate a random number between 0 and 9

# importing the random module
import random

print("haloo",random.randint(0,29))
print("butuh ide")
time.sleep(2)
print("bosen")
print("gini amat")
time.sleep(1)
print("ngapain ya")
time.sleep(0.5)
print("haloo nama saya\nmuhammad Rizki farez")
time.sleep(0.5)
namamu = input("namamu sapa?")
time.sleep(0.5)
print("oh namamu",namamu)
time.sleep(2.4)
print("Bosen amat")
print("cuman bisa print doang")
#bosen

#python

user_input = input("Please input umurmu") 
 
try: 
    age = int(user_input) 
except ValueError: 
    print("umurmu harus angka") 
 
if age > 18: 
    print("sudah besar") 
else: 
    print("masih bocah") 
  
namamu = input("apakah anda ingin melihat angka keberuntungan")   
print("melihat angka keberuntungan anda")
time.sleep(2.5)
print("angka keberuntungan anda:",random.randint(0,1001))

user_input = input("1+1 berapa?") 
 
try: 
    age = int(user_input) 
except ValueError: 
    print("harus angka") 
 
if age > 2: 
    print("Pinter") 
else: 
    print("goblokk") 

print("plisss gw stresss")
print("plisss gw stresss")
print("plisss gw stresss")
print("plisss gw stresss")
print("plisss gw stresss")
print("plisss gw stresss")
print("======================")
print("plisss gw stresss")
print("plisss gw stresss")
print("plisss gw stresss")
print("                 ")
print("saya abis buat marah orang")
time.sleep(3)
print("connected to server")
time.sleep(2)
print("succes to connected")
print(".                  ")
print("~~~~~~~~~~~~~~nasa hengker~~~~~~~~~~~~~~")
if input('TYPE "start" untuk memulai hacking .\n> ') == 'start': 
 import time
time.sleep(3)
print("memulai menyambung ke tools ")
time.sleep(2)
print("PROCESS STARTED! ")
print(".     ")
time.sleep(1)
akun = input("wifi name")
time.sleep(1)
print("memulai menghack password wifi bernama",akun)
time.sleep(0.3)
print("hacking")
time.sleep(0.5)
print("hacking")
time.sleep(0.5)
print("hacking")
time.sleep(0.5)
print("hacking")
time.sleep(0.5)
print("hacking")
time.sleep(0.5)
print("hacking")
time.sleep(0.5)
print("hacking")
time.sleep(0.5)
print("hacking")
time.sleep(0.5)
print("hacking")
time.sleep(0.5)
print("hacking")
time.sleep(0.5)
print("hacking")
time.sleep(1.5)
print("succes   !")
print("          ")

hacking = input("ingin melihat password wifi?")
time.sleep(0.5)
print("memulai  !")
time.sleep(0.5)
print("password Yesgahaa1233 failed!")
time.sleep(0.5)
print("PIN 729293 FAILD! ")
time.sleep(0.5)
print("PIN 74397493 FAILD! ")
time.sleep(0.5)
print("PIN 738349 FAILD! ")
time.sleep(0.5)
print("PIN 37383 FAILD! ")
time.sleep(0.5)
print("PIN 8320293 FAILD! ")
time.sleep(0.5)
print("PIN 833920 FAILD! ")
time.sleep(0.5)
print("PIN 38383 FAILD! ")
time.sleep(0.5)
print("PIN 38383 FAILD! ")
time.sleep(0.5)
print("PIN 483939 FAILD! ")
time.sleep(0.5)
print("PIN 4939339 FAILD! ")
time.sleep(0.5)
print("PIN 38339 FAILD! ")
time.sleep(0.5)
print("PIN 4933930 FAILD! ")
time.sleep(0.5)
print("PIN 49493939 FAILD! ")
time.sleep(0.5)
print("PIN 493933493 FAILD! ")
time.sleep(0.5)
print("PIN 4943903 FAILD! ")
time.sleep(0.5)
print("PIN 484394949 FAILD! ")
time.sleep(0.5)
print("PIN 392837 FAILD! ")
time.sleep(0.5)
print("PIN 20284383 FAILD! ")
time.sleep(0.5)
print("PIN 7348383 FAILD! ")
time.sleep(0.5)
print("PIN 38383899 FAILD! ")
time.sleep(0.5)
print("PIN 7819479 FAILD! ")
time.sleep(0.5)
print("PIN 28395040 FAILD! ")
time.sleep(0.5)
print("PIN 485740330 FAILD! ")
time.sleep(0.5)
print("PIN 37393959 FAILD! ")
time.sleep(0.5)
print("PIN 74384848 FAILD! ")
time.sleep(0.5)
print("PIN 17484930 FAILD! ")
time.sleep(0.5)
print("PIN 1234695 FAILD! ")
time.sleep(0.5)
print("PIN 8393929348 FAILD! ")
time.sleep(0.5)
print("PIN 382930505 FAILD! ")
time.sleep(0.5)
print("PIN 3833895 FAILD! ")
time.sleep(0.5)
print("PIN 494949 FAILD! ")
time.sleep(0.5)
print("PIN 484959 FAILD! ")
time.sleep(0.5)
print("PIN 4939506 FAILD! ")
time.sleep(0.5)
print("PIN 3849590 FAILD! ")
time.sleep(0.5)
print("PIN 48393949 FAILD! ")
time.sleep(0.5)
print("PIN 38485060 FAILD! ")
time.sleep(0.5)
print("PIN 39302058 FAILD! ")
time.sleep(0.5)
print("PIN 3830595o FAILD! ")
time.sleep(0.5)
print("PIN 830350648 FAILD! ")
time.sleep(0.5)
print("PIN 48539495 FAILD! ")
time.sleep(0.5)
print("PIN 48496063 FAILD! ")
time.sleep(0.5)
print("PIN 123456789 FAILD! ")
time.sleep(0.5)
print("PIN 0123456789 FAILD! ")
time.sleep(0.5)
print("PIN 0 WORK! ")
time.sleep(2)
print("                                                     ")
print("password ditemukan ")
time.sleep(1.8)
print("memulai ")






print("        ")
print("        ")
time.sleep(0.3)
print("%1")
time.sleep(0.3)
print("%15")
time.sleep(0.3)
print("%20")
time.sleep(0.3)
print("%25")
time.sleep(0.3)
print("%30")
time.sleep(0.3)
print("%35")
time.sleep(0.5)
print("%47")
time.sleep(0.4)
print("%51")
time.sleep(0.2)
print("%60")
time.sleep(0.9)
print("%63")
time.sleep(0.6)
print("%78")
time.sleep(0.3)
print("%80")
time.sleep(0.3)
print("%85")
time.sleep(0.1)
print("%90")
time.sleep(0.8)
print("%97")
time.sleep(0.7)
print("%99")
time.sleep(1)
print("%100")
time.sleep(1.5)
print("succes     !")
print("            ")

jaja = input("ingin lihat password?")
time.sleep(2.5)
source = string.ascii_letters + string.digits
result_str = ''.join((random.choice(source) for i in range(8)))
print("passwordnya adalah",result_str)

jey = input("apakah kamu ganteng")
time.sleep(0.5)
print("=============================")
print("plsss gw stres")
print("=============================")

print("hahaaaa")
print("me hengker pro")
time.sleep(1)
print("1%")
time.sleep(0.5)
print("10%")
time.sleep(0.5)
print("15%")
time.sleep(0.5)
print("20%")
time.sleep(0.5)
print("25%")
time.sleep(0.5)
print("30%")
time.sleep(0.5)
print("48%")
time.sleep(0.7)
print("67%")
time.sleep(0.7)
print("78%")
time.sleep(0.7)
print("89%")
time.sleep(0.7)
print("98%")
time.sleep(1)
print("100%")
time.sleep(2.5)
print("selamat jadi hengker pro")
time.sleep(2)
print("Farez gantengg")
print("wkwkwkkw")
iki = input("apakah Farez ganteng")
time.sleep(1)
print("stresss")
